# Generated by Django 6.0.4 on 2026-04-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_usuariorestaurante_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='email_notificacion',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='notificar_reservas',
            field=models.BooleanField(default=True),
        ),
    ]
