# Generated by Django 6.0.4 on 2026-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_restaurante_email_notificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='google_maps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='link_delivery',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
