# Generated by Django 6.0.4 on 2026-04-30 18:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_respaldorestaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img_categoria',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='img'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='mensaje_bienvenida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='slogan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='theme_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
