# Generated by Django 6.0.4 on 2026-04-30 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_remove_categoria_img_categoria_categoria_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clase_css', models.CharField(help_text='Clase de Bootstrap Icons. Ej: bi-egg-fried', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='menu.icono'),
        ),
    ]
