# Generated by Django 6.0.4 on 2026-05-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_icono_alter_categoria_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='icono',
            name='clase_css',
            field=models.CharField(help_text='Clase de Font Awesome. Ej: bi-egg-fried', max_length=50, unique=True),
        ),
    ]
