# Generated by Django 6.0.4 on 2026-05-02 02:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_producto_clicks_alter_icono_clase_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imgen_principal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_principal'),
        ),
    ]
