# Generated by Django 6.0.4 on 2026-05-02 07:50

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_restaurante_imgen_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ej: portada, galeria, interior, comida, etc', max_length=100)),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='menu.restaurante')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
