# Generated by Django 6.0.4 on 2026-05-03 02:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_imagenrestaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imgen_form',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_form'),
        ),
    ]
