# Generated by Django 6.0.4 on 2026-05-06 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_restaurante_imgen_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
