# Generated by Django 6.0.4 on 2026-06-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('telefono_cliente', models.CharField(max_length=30)),
                ('tipo_entrega', models.CharField(choices=[('delivery', 'Delivery'), ('retiro_local', 'Retiro en local'), ('para_llevar', 'Para llevar')], max_length=20)),
                ('productos_snapshot', models.JSONField()),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje_whatsapp_generado', models.TextField()),
                ('whatsapp_destino', models.CharField(max_length=30)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_whatsapp', to='menu.restaurante')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['restaurante', '-fecha_creacion'], name='pedw_rest_fecha_idx'), models.Index(fields=['restaurante', 'estado'], name='pedw_rest_estado_idx')],
            },
        ),
    ]
