# Generated by Django 6.0.4 on 2026-06-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_pedidos_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidowhatsapp',
            name='direccion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
    ]
