# Generated by Django 6.0.4 on 2026-06-07 01:00

import django.db.models.deletion
from django.db import migrations, models


def crear_planes_iniciales(apps, schema_editor):
    Plan = apps.get_model("menu", "Plan")
    Restaurante = apps.get_model("menu", "Restaurante")

    planes = [
        ("Básico", "basico", "Plan inicial con métricas básicas."),
        ("Pro", "pro", "Plan con métricas avanzadas y reportes."),
        ("Full Pro", "full_pro", "Plan Pro con estructura para herramientas IA."),
    ]

    for nombre, slug, descripcion in planes:
        Plan.objects.update_or_create(
            slug=slug,
            defaults={
                "nombre": nombre,
                "descripcion": descripcion,
                "activo": True,
            },
        )

    plan_basico = Plan.objects.get(slug="basico")
    Restaurante.objects.filter(plan__isnull=True).update(plan=plan_basico)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_pedidowhatsapp_direccion_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='restaurante',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurantes', to='menu.plan'),
        ),
        migrations.RunPython(crear_planes_iniciales, reverse_code=migrations.RunPython.noop),
    ]
