# Generated by Django 6.0.4 on 2026-06-07 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_plan_restaurante_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20)),
                ('periodo_mes', models.CharField(blank=True, max_length=7, null=True)),
                ('periodo_anio', models.CharField(blank=True, max_length=4, null=True)),
                ('titulo', models.CharField(max_length=180)),
                ('resumen', models.JSONField(default=dict)),
                ('datos', models.JSONField(default=dict)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes_metricas/')),
                ('activo', models.BooleanField(default=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_metricas_generados', to=settings.AUTH_USER_MODEL)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_metricas', to='menu.restaurante')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['restaurante', 'tipo', '-fecha_generacion'], name='repmet_rest_tipo_fecha_idx'), models.Index(fields=['restaurante', 'periodo_mes'], name='repmet_rest_mes_idx'), models.Index(fields=['restaurante', 'periodo_anio'], name='repmet_rest_anio_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo', 'mensual')), fields=('restaurante', 'tipo', 'periodo_mes'), name='unique_reporte_mensual_rest_periodo'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo', 'anual')), fields=('restaurante', 'tipo', 'periodo_anio'), name='unique_reporte_anual_rest_periodo')],
            },
        ),
    ]
