# Generated by Django 6.0.4 on 2026-06-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_pedido_whatsapp_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='referencia_modelo',
            field=models.CharField(choices=[('Reserva', 'Reserva'), ('SolicitudEspecial', 'Solicitud especial'), ('PedidoWhatsApp', 'Pedido WhatsApp'), ('PedidoEspecial', 'Pedido especial')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('reserva', 'Reserva'), ('solicitud_especial', 'Solicitud especial'), ('pedido', 'Pedido')], max_length=30),
        ),
    ]
