# Generated by Django 6.0.4 on 2026-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_restaurante_delivery_abierto_pedidowhatsapp_en_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidowhatsapp',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Pedido recibido'), ('pendiente_confirmacion', 'Pendiente de confirmacion'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_delivery', 'En camino'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=30),
        ),
    ]
