# Generated by Django 6.0.4 on 2026-07-11 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_pedidowhatsapp_en_reparto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.PositiveIntegerField()),
                ('origen', models.CharField(choices=[('menly', 'Menly')], default='menly', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('nombre_cliente', models.CharField(blank=True, max_length=120)),
                ('telefono_cliente', models.CharField(blank=True, max_length=30)),
                ('tipo_entrega', models.CharField(choices=[('mesa', 'Mesa'), ('retiro', 'Retiro'), ('delivery', 'Delivery'), ('para_llevar', 'Para llevar')], max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('numero_mesa', models.CharField(blank=True, max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_manuales_creados', to=settings.AUTH_USER_MODEL)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_manuales', to='menu.restaurante')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoManualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.pedidomanual')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pedidos_manuales', to='menu.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidomanual',
            index=models.Index(fields=['restaurante', '-fecha_creacion'], name='pedman_rest_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidomanual',
            index=models.Index(fields=['restaurante', 'estado'], name='pedman_rest_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidomanual',
            constraint=models.UniqueConstraint(fields=('restaurante', 'numero_pedido'), name='unique_pedido_manual_numero_por_rest'),
        ),
        migrations.AddIndex(
            model_name='pedidomanualitem',
            index=models.Index(fields=['pedido'], name='pedman_item_pedido_idx'),
        ),
    ]
