# Generated by Django 6.0.4 on 2026-07-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0045_restaurante_apertura_excepcional_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoIdempotencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado')], default='procesando', max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pedido_whatsapp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotencia', to='menu.pedidowhatsapp')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotencias_pedidos', to='menu.restaurante')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('restaurante', 'clave'), name='unique_idempotencia_pedido_por_rest')],
            },
        ),
    ]
